//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremptyWorkSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Areas
    {
        public Areas()
        {
            this.Usuarios = new HashSet<Usuarios>();
            this.Eventos = new HashSet<Eventos>();
        }
    
        public int IdArea { get; set; }
        public string Descripcion { get; set; }
        public int IdEntidad { get; set; }
    
        public virtual ICollection<Usuarios> Usuarios { get; set; }
        public virtual Entidades Entidades { get; set; }
        public virtual ICollection<Eventos> Eventos { get; set; }
    }
}
