//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremptyWorkSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entidades
    {
        public Entidades()
        {
            this.Areas = new HashSet<Areas>();
            this.Eventos = new HashSet<Eventos>();
            this.MotivoLicencia = new HashSet<MotivoLicencia>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int IdEntidad { get; set; }
        public string RazonSocial { get; set; }
        public string Cuit { get; set; }
        public string Domicilio { get; set; }
        public string Telefono { get; set; }
        public string Categoria { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
    
        public virtual ICollection<Areas> Areas { get; set; }
        public virtual ICollection<Eventos> Eventos { get; set; }
        public virtual ICollection<MotivoLicencia> MotivoLicencia { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
