//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremptyWorkSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos
    {
        public Eventos()
        {
            this.Respuestas = new HashSet<Respuestas>();
        }
    
        public int IdEventos { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> IdArea { get; set; }
        public string Tipo { get; set; }
        public int IdEntidad { get; set; }
    
        public virtual Areas Areas { get; set; }
        public virtual Entidades Entidades { get; set; }
        public virtual ICollection<Respuestas> Respuestas { get; set; }
    }
}
