//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremptyWorkSpace.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Eventos
    {
        public Eventos()
        {
            this.Respuestas = new HashSet<Respuestas>();
        }

        public int IdEventos { get; set; }
        [Required(ErrorMessage = "Debe ingresar un titulo")]
        public string Titulo { get; set; }
        [Required(ErrorMessage = "Debe ingresar una descripcion")]
        public string Descripcion { get; set; }
        [Required(ErrorMessage = "Debe ingresar una fecha")]
        [DataType(DataType.DateTime)]
        public System.DateTime Fecha { get; set; }
        [Required(ErrorMessage = "Debe seleccionar un area")]
        public Nullable<int> IdArea { get; set; }
        public string Tipo { get; set; }
        public int IdEntidad { get; set; }

        public virtual Areas Areas { get; set; }
        public virtual Entidades Entidades { get; set; }
        public virtual ICollection<Respuestas> Respuestas { get; set; }
    }
}
