//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremptyWorkSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingresos
    {
        public int IdIngresos { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaActual { get; set; }
        public Nullable<System.DateTime> HoraIngreso { get; set; }
        public Nullable<System.DateTime> HoraEgreso { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
