//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremptyWorkSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licencias
    {
        public int IdLicencia { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> Motivo { get; set; }
        public string Descripcion { get; set; }
        public int Estado { get; set; }
    
        public virtual MotivoLicencia MotivoLicencia { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
