//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremptyWorkSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotivoLicencia
    {
        public MotivoLicencia()
        {
            this.Licencias = new HashSet<Licencias>();
        }
    
        public int IdMotivo { get; set; }
        public string Descripcion { get; set; }
        public int IdEntidad { get; set; }
    
        public virtual Entidades Entidades { get; set; }
        public virtual ICollection<Licencias> Licencias { get; set; }
    }
}
