//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremptyWorkSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotivoLicencia
    {
        public MotivoLicencia()
        {
            this.Licencias = new HashSet<Licencias>();
        }
    
        public int IdMotivo { get; set; }
        public string Descripcion { get; set; }
        public int IdEntidad { get; set; }
    
        public virtual Entidades Entidades { get; set; }
        public virtual ICollection<Licencias> Licencias { get; set; }
    }
}
