//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremptyWorkSpace.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PremptyDb : DbContext
    {
        public PremptyDb()
            : base("name=PremptyDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Areas> Areas { get; set; }
        public DbSet<Entidades> Entidades { get; set; }
        public DbSet<Eventos> Eventos { get; set; }
        public DbSet<Ingresos> Ingresos { get; set; }
        public DbSet<Licencias> Licencias { get; set; }
        public DbSet<MotivoLicencia> MotivoLicencia { get; set; }
        public DbSet<Respuestas> Respuestas { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
        public DbSet<Feriados> Feriados { get; set; }
    }
}
