//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremptyWorkSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuestas
    {
        public int IdRespuesta { get; set; }
        public int IdEvento { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<int> Respuesta { get; set; }
        public string Comentario { get; set; }
    
        public virtual Eventos Eventos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
