//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremptyWorkSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int IdRol { get; set; }
        public string Rol { get; set; }
    
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
