//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremptyWorkSpace.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Ingresos = new HashSet<Ingresos>();
            this.Licencias = new HashSet<Licencias>();
            this.Respuestas = new HashSet<Respuestas>();
        }

        public int IdUsuario { get; set; }
        [Required(ErrorMessage = "Debe seleccionar un rol")]
        public int IdRol { get; set; }
        [Required(ErrorMessage = "Debe ingresar un numero de legajo")]
        public Nullable<int> Legajo { get; set; }
        [Required(ErrorMessage = "Debe ingresar un nombre")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "Debe ingresar un apellido")]
        public string Apellido { get; set; }
        [DisplayName("Fecha de nacimiento")]
        [Required(ErrorMessage = "Debe ingresar una fecha de nacimiento")]
        public System.DateTime FechaNac { get; set; }
        [Required(ErrorMessage = "Debe ingresar una fecha de ingreso")]
        [DisplayName("Fecha de Ingreso")]
        public System.DateTime FechaIngreso { get; set; }
        [Required(ErrorMessage = "Debe seleccionar un area")]
        public int IdArea { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Debe ingresar una contraseña")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Debe ingresar un domicilio")]
        public string Domicilio { get; set; }
        [Required(ErrorMessage = "Debe ingresar un nombre de usuario")]
        [DisplayName("Nombre de usuario")]
        public string NombreUsuario { get; set; }
        public int IdEntidad { get; set; }
        [RegularExpression(@"^[0-9a-zA-Z]([-\.\w]*[0-9a-zA-Z])*@(ua)\.(es)$",
            ErrorMessage = "El formato del correo es incorrecto.")]
        public string Email { get; set; }

        public virtual Areas Areas { get; set; }
        public virtual Entidades Entidades { get; set; }
        public virtual ICollection<Ingresos> Ingresos { get; set; }
        public virtual ICollection<Licencias> Licencias { get; set; }
        public virtual ICollection<Respuestas> Respuestas { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
