//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremptyWorkSpace.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Ingresos = new HashSet<Ingresos>();
            this.Licencias = new HashSet<Licencias>();
            this.Respuestas = new HashSet<Respuestas>();
        }

        public int IdUsuario { get; set; }
        public int IdRol { get; set; }
        public Nullable<int> Legajo { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime FechaNac { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime FechaIngreso { get; set; }
        public int IdArea { get; set; }
        public string Password { get; set; }
        public string Domicilio { get; set; }

        public string NombreUsuario { get; set; }
        public int IdEntidad { get; set; }
        public string Email { get; set; }

        public virtual Areas Areas { get; set; }
        public virtual Entidades Entidades { get; set; }
        public virtual ICollection<Ingresos> Ingresos { get; set; }
        public virtual ICollection<Licencias> Licencias { get; set; }
        public virtual ICollection<Respuestas> Respuestas { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
